//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "ricky firmansyah",
    "email": "admin@mail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "admin"
}

###
//create user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Edi Kurniawan",
    "email": "user@mail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "user"
}

###
//get All Users
GET http://localhost:5000/users

###
//get single user
GET http://localhost:5000/users/37f5613d-e5b5-4122-908f-4580a43615d2

###
//Update User
PATCH http://localhost:5000/users/2897a237-fe8e-47aa-aaed-a696e816ea76
Content-Type: application/json

{
    "name": "User Testing",
    "email": "user@mail.com",
    "password": "user123",
    "confPassword": "user123",
    "role": "user"
}

###
//Delete User
DELETE http://localhost:5000/users/7b8b9ff2-7b7a-49ec-aeb1-2e0113991dbd


###
//Login Admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "215100036p@umitra.ac.id",
    "password": "123456"
}

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
//cek User
GET http://localhost:5000/me

###
//Logout
DELETE http://localhost:5000/logout

###
//get All Product
GET http://localhost:5000/products

###
//get single Product
GET http://localhost:5000/products/c4c9503a-391b-44bd-8bda-ef7a4d984014


###
//POST data product
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "product 6",
    "price": "987"
}

###
//Update data product
PATCH http://localhost:5000/products/c4c9503a-391b-44bd-8bda-ef7a4d984014
Content-Type: application/json

{
    "name": "product 6 up",
    "price": "984"
}

###
//Update data product
DELETE http://localhost:5000/products/1c006b4f-5143-494f-986d-f4cb6332d499